sudo: false
matrix:
  include:
  - language: node_js
    node_js:
      - 12.13.0
    before_install:
      # alias python3.7.1 to python3
      - pyenv global 3.7.1
    install:
      - npm install
    script:
      - npm run lint
      - npm run stylelint
      - npm run markdownlint
      - npm test

  - language: python
    python:
      - 3.6
    install:
      - pip install pylint==2.2.3 requests==2.22.0 PyYAML==5.1.2 black==19.10b0
    script:
      - pylint **/*.py --errors-only
      - black **/*.py --line-length 100 --check --diff
