name: Update gh-pages

on:
  push:
    branches: [ main ]

jobs:
  check-gh-pages:
    runs-on: ubuntu-latest
    outputs:
      found: ${{ steps.check-gh-pages.outputs.found }}
    steps:
      - name: Check gh-pages Exists
        id: check-gh-pages
        shell: bash
        run: |
          GITHUB_URL="https://github.com/${{ github.repository }}"
          if git ls-remote --exit-code --heads $GITHUB_URL gh-pages; then
            echo "::set-output name=found::true"
            echo "gh-pages branch found. Updating..."
          else
            echo "::set-output name=found::false"
            echo "gh-pages branch not found. Skipping..."
          fi
  update-gh-pages:
    runs-on: ubuntu-latest
    needs: check-gh-pages
    if: needs.check-gh-pages.outputs.found == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build
        run: |
          npm install
          npm run coverage-report
          npm run build
      - name: git setup
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: git commit and push
        run: |
          git checkout -B gh-pages
          git add dist resources --force
          git commit -m "gh-pages build"
          git push origin gh-pages --force
